blank_issues_enabled: true
contact_links:
  - name: Submit issues about Minetest Game
    url: https://github.com/minetest/minetest_game/issues/new/choose
    about: Only submit issues of the engine in this repository's issue tracker. Submit those of Minetest Game in its own issue tracker.
  - name: Search for issue trackers of third-party subgames
    url: https://content.minetest.net/packages/?type=game
    about: For issues of third-party games, search for their issue trackers in the ContentDB.