name: lint

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [ push, pull_request ]

jobs:
  clang_format:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install clang-format
        run: |
          sudo apt-get install ${CLANG_FORMAT} -qyy
        env:
          CLANG_FORMAT: clang-format-9
      - name: Run clang-format
        run: |
          source ./util/ci/lint.sh
          perform_lint

  clang_tidy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install clang-tidy
      run: |
        sudo apt-get install clang-tidy-9 -qyy
        source ./util/ci/common.sh
        install_linux_deps

    - name: Run clang-tidy
      run: |
        ./util/ci/clang-tidy.sh

  luacheck:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install luarocks
      run: |
        sudo apt-get update -qyy
        sudo apt-get install luarocks -qyy

    - name: Install luarocks tools
      run: |
        luarocks install --local luacheck
        luarocks install --local busted

    - name: Run checks
      run: |
        $HOME/.luarocks/bin/luacheck builtin
        $HOME/.luarocks/bin/busted builtin
