name: macos_11_arm64

# build on c/cpp changes or workflow changes
on:
  push:
    paths:
      - 'lib/**.[ch]'
      - 'lib/**.cpp'
      - 'src/**.[ch]'
      - 'src/**.cpp'
      - 'irr/**.[ch]'
      - 'irr/**.cpp'
      - 'irr/**.mm' # Objective-C(++)
      - '**/CMakeLists.txt'
      - 'cmake/Modules/**'
      - 'util/ci/macos_build_deps.sh'
      - '.github/workflows/macos_11_arm64.yml'
  pull_request:
    paths:
      - 'lib/**.[ch]'
      - 'lib/**.cpp'
      - 'src/**.[ch]'
      - 'src/**.cpp'
      - 'irr/**.[ch]'
      - 'irr/**.cpp'
      - 'irr/**.mm' # Objective-C(++)
      - '**/CMakeLists.txt'
      - 'cmake/Modules/**'
      - 'util/ci/macos_build_deps.sh'
      - '.github/workflows/macos_11_arm64.yml'

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          source ./util/ci/macos_build_deps.sh 
          echo "GETTING SDK"
          download_macos_sdk "11"
          echo "GETTING LIBRARY SOURCES"
          download_macos_deps
          echo "UNARCHIVING LIBRARY SOURCES"
          untar_macos_deps
          echo "COMPILING LIBRARIES"
          compile_macos_deps "arm64" "11"

      - name: Build
        run: |
          mkdir build
          cd build
          export CMAKE_PREFIX_PATH=$(realpath ../deps/install)
          export SDKROOT=$(realpath ../deps/MacOSX11.sdk)
          cmake .. \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=11 \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DCMAKE_FIND_FRAMEWORK=LAST \
            -DCMAKE_INSTALL_PREFIX=../build/macos/ \
            -DRUN_IN_PLACE=FALSE -DENABLE_GETTEXT=TRUE \
            -DINSTALL_DEVTEST=TRUE
          cmake --build . -j$(sysctl -n hw.logicalcpu)
          make install

      - name: Test
        run: |
          ./build/macos/minetest.app/Contents/MacOS/minetest --run-unittests

      # Zipping the built .app preserves permissions on the contained files,
      #   which the GitHub artifact pipeline would otherwise strip away.
      - name: CPack
        run: |
          cd build
          rm -rf macos
          cmake .. -DINSTALL_DEVTEST=FALSE
          cpack -G ZIP -B macos

      - uses: actions/upload-artifact@v4
        with:
          name: minetest-macos_11_arm64
          path: ./build/macos/*.zip
