name: macos

# build on c/cpp changes or workflow changes
on:
  push:
    paths:
      - 'lib/**.[ch]'
      - 'lib/**.cpp'
      - 'src/**.[ch]'
      - 'src/**.cpp'
      - 'irr/**.[ch]'
      - 'irr/**.cpp'
      - 'irr/**.mm' # Objective-C(++)
      - '**/CMakeLists.txt'
      - 'cmake/Modules/**'
      - '.github/workflows/macos.yml'
  pull_request:
    paths:
      - 'lib/**.[ch]'
      - 'lib/**.cpp'
      - 'src/**.[ch]'
      - 'src/**.cpp'
      - 'irr/**.[ch]'
      - 'irr/**.cpp'
      - 'irr/**.mm' # Objective-C(++)
      - '**/CMakeLists.txt'
      - 'cmake/Modules/**'
      - '.github/workflows/macos.yml'

jobs:
  build-intel-macos:
    # use lowest possible macOS running on x86_64 supported by brew to support more users
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          source ./util/ci/common.sh
          install_macos_deps

      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=10.14 \
            -DCMAKE_FIND_FRAMEWORK=LAST \
            -DCMAKE_INSTALL_PREFIX=../build/macos/ \
            -DRUN_IN_PLACE=FALSE -DENABLE_GETTEXT=TRUE \
            -DINSTALL_DEVTEST=TRUE
          cmake --build . -j$(sysctl -n hw.logicalcpu)
          make install

      - name: Test
        run: |
          ./build/macos/luanti.app/Contents/MacOS/luanti --run-unittests

      # Zipping the built .app preserves permissions on the contained files,
      #   which the GitHub artifact pipeline would otherwise strip away.
      - name: CPack
        run: |
          cd build
          rm -rf macos
          cmake .. -DINSTALL_DEVTEST=FALSE
          cpack -G ZIP -B macos

      - uses: actions/upload-artifact@v4
        with:
          name: luanti-macos
          path: ./build/macos/*.zip
  build-arm-macos-xcode:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          source ./util/ci/common.sh
          install_macos_deps
          # brew jsoncpp do not include libjsoncpp.a, and if installed header conflict caused build failure
          brew uninstall jsoncpp

      - name: Build with Cmake
        run: |
          mkdir build
          cd build
          cmake .. \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=14 \
            -DCMAKE_FIND_FRAMEWORK=LAST \
            -DCMAKE_INSTALL_PREFIX=../build/macos/ \
            -DRUN_IN_PLACE=FALSE -DENABLE_GETTEXT=TRUE \
            -DENABLE_SYSTEM_JSONCPP=OFF
          cmake --build . -j$(sysctl -n hw.logicalcpu)
          make install

      - name: Build and Archive with Xcode
        run: |
          mkdir build_xcode
          cd build_xcode
          cmake .. \
            -DCMAKE_FIND_FRAMEWORK=LAST \
            -DRUN_IN_PLACE=FALSE -DENABLE_GETTEXT=TRUE \
            -DFREETYPE_LIBRARY=/opt/homebrew/lib/libfreetype.a \
            -DGETTEXT_INCLUDE_DIR=/path/to/include/dir \
            -DGETTEXT_LIBRARY=/opt/homebrew/lib/libintl.a \
            -DLUA_LIBRARY=/opt/homebrew/lib/libluajit-5.1.a \
            -DOGG_LIBRARY=/opt/homebrew/lib/libogg.a \
            -DVORBIS_LIBRARY=/opt/homebrew/lib/libvorbis.a \
            -DVORBISFILE_LIBRARY=/opt/homebrew/lib/libvorbisfile.a \
            -DZSTD_LIBRARY=/opt/homebrew/lib/libzstd.a \
            -DGMP_LIBRARY=/opt/homebrew/lib/libgmp.a \
            -DENABLE_SYSTEM_JSONCPP=OFF \
            -DENABLE_LEVELDB=OFF \
            -DENABLE_POSTGRESQL=OFF \
            -DENABLE_REDIS=OFF \
            -DJPEG_LIBRARY=/opt/homebrew/lib/libjpeg.a \
            -DPNG_LIBRARY=/opt/homebrew/lib/libpng.a \
            -DCMAKE_EXE_LINKER_FLAGS=-lbz2\
            -GXcode
          xcodebuild -project luanti.xcodeproj -scheme luanti -configuration Release build
          xcodebuild -project luanti.xcodeproj -scheme luanti -archivePath ./luanti.xcarchive archive

      - name: Tests
        run: |
          mkdir -p "${HOME}/Library/Application Support/minetest/games/"
          ln -s "${PWD}/games/devtest" "${HOME}/Library/Application Support/minetest/games/"
          ./build/macos/luanti.app/Contents/MacOS/luanti --run-unittests
          ./build_xcode/build/Release/luanti.app/Contents/MacOS/luanti --run-unittests
          ./build_xcode/luanti.xcarchive/Products/Applications/luanti.app/Contents/MacOS/luanti --run-unittests

      - name: Diff Resources
        run: |
          diff -rd ./build/macos/luanti.app/Contents/Resources ./build_xcode/build/Release/luanti.app/Contents/Resources || exit 1
          diff -rd ./build/macos/luanti.app/Contents/Resources ./build_xcode/luanti.xcarchive/Products/Applications/luanti.app/Contents/Resources || exit 1
